// Demo words for the flip / rating pages. Appearance only — any plausible
// data works.

import type { CardData } from '../../components/FlipDeck'

export const WORDS: CardData[] = [
  { word: 'abandon', phonetic: '/əˈbændən/', senses: [{ pos: 'v.', defs: ['放弃', '抛弃'] }], tags: ['CET4'] },
  { word: 'benevolent', phonetic: '/bəˈnevələnt/', senses: [{ pos: 'adj.', defs: ['仁慈的', '善意的'] }], tags: ['CET6'] },
  { word: 'candid', phonetic: '/ˈkændɪd/', senses: [{ pos: 'adj.', defs: ['坦率的', '直言的'] }], tags: ['CET6'] },
  { word: 'diligent', phonetic: '/ˈdɪlɪdʒənt/', senses: [{ pos: 'adj.', defs: ['勤勉的', '用功的'] }], tags: ['CET4'] },
  { word: 'eloquent', phonetic: '/ˈeləkwənt/', senses: [{ pos: 'adj.', defs: ['雄辩的', '有说服力的'] }], tags: ['CET6'] },
  { word: 'frugal', phonetic: '/ˈfruːɡl/', senses: [{ pos: 'adj.', defs: ['节俭的', '朴素的'] }], tags: ['CET6'] },
  { word: 'genuine', phonetic: '/ˈdʒenjuɪn/', senses: [{ pos: 'adj.', defs: ['真诚的', '真正的'] }], tags: ['CET4'] },
  { word: 'humble', phonetic: '/ˈhʌmbl/', senses: [{ pos: 'adj.', defs: ['谦逊的', '卑微的'] }], tags: ['CET4'] },
  { word: 'lucid', phonetic: '/ˈluːsɪd/', senses: [{ pos: 'adj.', defs: ['清晰的', '明白易懂的'] }], tags: ['CET6'] },
  { word: 'meticulous', phonetic: '/məˈtɪkjələs/', senses: [{ pos: 'adj.', defs: ['一丝不苟的', '细致的'] }], tags: ['CET6'] },
  { word: 'resilient', phonetic: '/rɪˈzɪliənt/', senses: [{ pos: 'adj.', defs: ['有韧性的', '能恢复的'] }], tags: ['CET6'] },
  { word: 'vivid', phonetic: '/ˈvɪvɪd/', senses: [{ pos: 'adj.', defs: ['生动的', '鲜明的'] }], tags: ['CET4'] },
  { word: 'abrupt', phonetic: '/əˈbrʌpt/', senses: [{ pos: 'adj.', defs: ['突然的', '唐突的'] }], tags: ['CET4'] },
  { word: 'amplify', phonetic: '/ˈæmplɪfaɪ/', senses: [{ pos: 'v.', defs: ['放大', '增强'] }], tags: ['CET6'] },
  { word: 'arbitrary', phonetic: '/ˈɑːbɪtrəri/', senses: [{ pos: 'adj.', defs: ['任意的', '武断的'] }], tags: ['CET6'] },
  { word: 'articulate', phonetic: '/ɑːˈtɪkjuleɪt/', senses: [{ pos: 'adj.', defs: ['表达清晰的'] }, { pos: 'v.', defs: ['清晰地表达'] }], tags: ['CET6'] },
  { word: 'authentic', phonetic: '/ɔːˈθentɪk/', senses: [{ pos: 'adj.', defs: ['真实的', '可信的'] }], tags: ['CET4'] },
  { word: 'benign', phonetic: '/bɪˈnaɪn/', senses: [{ pos: 'adj.', defs: ['良性的', '和善的'] }], tags: ['CET6'] },
  { word: 'bleak', phonetic: '/bliːk/', senses: [{ pos: 'adj.', defs: ['荒凉的', '暗淡的'] }], tags: ['CET6'] },
  { word: 'brisk', phonetic: '/brɪsk/', senses: [{ pos: 'adj.', defs: ['轻快的', '活跃的'] }], tags: ['CET4'] },
  { word: 'coherent', phonetic: '/kəʊˈhɪərənt/', senses: [{ pos: 'adj.', defs: ['连贯的', '有条理的'] }], tags: ['CET6'] },
  { word: 'concise', phonetic: '/kənˈsaɪs/', senses: [{ pos: 'adj.', defs: ['简洁的', '简明的'] }], tags: ['CET6'] },
  { word: 'conspicuous', phonetic: '/kənˈspɪkjuəs/', senses: [{ pos: 'adj.', defs: ['显眼的', '引人注目的'] }], tags: ['CET6'] },
  { word: 'crucial', phonetic: '/ˈkruːʃl/', senses: [{ pos: 'adj.', defs: ['关键的', '至关重要的'] }], tags: ['CET4'] },
  { word: 'cumulative', phonetic: '/ˈkjuːmjələtɪv/', senses: [{ pos: 'adj.', defs: ['累积的', '渐增的'] }], tags: ['CET6'] },
  { word: 'deliberate', phonetic: '/dɪˈlɪbərət/', senses: [{ pos: 'adj.', defs: ['深思熟虑的', '故意的'] }], tags: ['CET6'] },
  { word: 'diminish', phonetic: '/dɪˈmɪnɪʃ/', senses: [{ pos: 'v.', defs: ['减少', '削弱'] }], tags: ['CET6'] },
  { word: 'discern', phonetic: '/dɪˈsɜːn/', senses: [{ pos: 'v.', defs: ['辨别', '察觉'] }], tags: ['CET6'] },
  { word: 'discreet', phonetic: '/dɪˈskriːt/', senses: [{ pos: 'adj.', defs: ['谨慎的', '慎重的'] }], tags: ['CET6'] },
  { word: 'elaborate', phonetic: '/ɪˈlæbərət/', senses: [{ pos: 'adj.', defs: ['精心制作的'] }, { pos: 'v.', defs: ['详述'] }], tags: ['CET6'] },
  { word: 'elusive', phonetic: '/ɪˈluːsɪv/', senses: [{ pos: 'adj.', defs: ['难以捉摸的', '逃避的'] }], tags: ['CET6'] },
  { word: 'eminent', phonetic: '/ˈemɪnənt/', senses: [{ pos: 'adj.', defs: ['杰出的', '著名的'] }], tags: ['CET6'] },
  { word: 'evoke', phonetic: '/ɪˈvəʊk/', senses: [{ pos: 'v.', defs: ['唤起', '引起'] }], tags: ['CET6'] },
  { word: 'explicit', phonetic: '/ɪkˈsplɪsɪt/', senses: [{ pos: 'adj.', defs: ['明确的', '清楚的'] }], tags: ['CET6'] },
  { word: 'feasible', phonetic: '/ˈfiːzəbl/', senses: [{ pos: 'adj.', defs: ['可行的', '行得通的'] }], tags: ['CET6'] },
  { word: 'fervent', phonetic: '/ˈfɜːvənt/', senses: [{ pos: 'adj.', defs: ['热情的', '强烈的'] }], tags: ['CET6'] },
  { word: 'formidable', phonetic: '/fəˈmɪdəbl/', senses: [{ pos: 'adj.', defs: ['强大的', '令人敬畏的'] }], tags: ['CET6'] },
  { word: 'futile', phonetic: '/ˈfjuːtaɪl/', senses: [{ pos: 'adj.', defs: ['徒劳的', '无效的'] }], tags: ['CET6'] },
  { word: 'gregarious', phonetic: '/ɡrɪˈɡeəriəs/', senses: [{ pos: 'adj.', defs: ['群居的', '爱社交的'] }], tags: ['CET6'] },
  { word: 'haphazard', phonetic: '/ˌhæpˈhæzəd/', senses: [{ pos: 'adj.', defs: ['随意的', '杂乱的'] }], tags: ['CET6'] },
  { word: 'imperative', phonetic: '/ɪmˈperətɪv/', senses: [{ pos: 'adj.', defs: ['必要的', '紧急的'] }], tags: ['CET6'] },
  { word: 'implicit', phonetic: '/ɪmˈplɪsɪt/', senses: [{ pos: 'adj.', defs: ['含蓄的', '暗含的'] }], tags: ['CET6'] },
  { word: 'intricate', phonetic: '/ˈɪntrɪkət/', senses: [{ pos: 'adj.', defs: ['复杂精细的', '错综的'] }], tags: ['CET6'] },
  { word: 'intrinsic', phonetic: '/ɪnˈtrɪnsɪk/', senses: [{ pos: 'adj.', defs: ['内在的', '固有的'] }], tags: ['CET6'] },
  { word: 'lucrative', phonetic: '/ˈluːkrətɪv/', senses: [{ pos: 'adj.', defs: ['有利可图的', '赚钱的'] }], tags: ['CET6'] },
  { word: 'magnitude', phonetic: '/ˈmæɡnɪtjuːd/', senses: [{ pos: 'n.', defs: ['重要性', '大小'] }], tags: ['CET6'] },
  { word: 'mundane', phonetic: '/mʌnˈdeɪn/', senses: [{ pos: 'adj.', defs: ['平凡的', '单调的'] }], tags: ['CET6'] },
  { word: 'notorious', phonetic: '/nəʊˈtɔːriəs/', senses: [{ pos: 'adj.', defs: ['臭名昭著的', '声名狼藉的'] }], tags: ['CET6'] },
  { word: 'obsolete', phonetic: '/ˈɒbsəliːt/', senses: [{ pos: 'adj.', defs: ['过时的', '淘汰的'] }], tags: ['CET6'] },
  { word: 'paramount', phonetic: '/ˈpærəmaʊnt/', senses: [{ pos: 'adj.', defs: ['至高无上的', '最重要的'] }], tags: ['CET6'] },
  { word: 'pragmatic', phonetic: '/præɡˈmætɪk/', senses: [{ pos: 'adj.', defs: ['务实的', '实用的'] }], tags: ['CET6'] },
  { word: 'profound', phonetic: '/prəˈfaʊnd/', senses: [{ pos: 'adj.', defs: ['深刻的', '深远的'] }], tags: ['CET4'] },
  { word: 'prolific', phonetic: '/prəˈlɪfɪk/', senses: [{ pos: 'adj.', defs: ['多产的', '丰富的'] }], tags: ['CET6'] },
  { word: 'prudent', phonetic: '/ˈpruːdnt/', senses: [{ pos: 'adj.', defs: ['谨慎的', '精明的'] }], tags: ['CET6'] },
  { word: 'redundant', phonetic: '/rɪˈdʌndənt/', senses: [{ pos: 'adj.', defs: ['多余的', '冗余的'] }], tags: ['CET6'] },
  { word: 'robust', phonetic: '/rəʊˈbʌst/', senses: [{ pos: 'adj.', defs: ['强健的', '稳固的'] }], tags: ['CET6'] },
  { word: 'scrutiny', phonetic: '/ˈskruːtəni/', senses: [{ pos: 'n.', defs: ['细看', '详细审查'] }], tags: ['CET6'] },
  { word: 'stagnant', phonetic: '/ˈstæɡnənt/', senses: [{ pos: 'adj.', defs: ['停滞的', '不流动的'] }], tags: ['CET6'] },
  { word: 'subtle', phonetic: '/ˈsʌtl/', senses: [{ pos: 'adj.', defs: ['微妙的', '细微的'] }], tags: ['CET4'] },
  { word: 'tedious', phonetic: '/ˈtiːdiəs/', senses: [{ pos: 'adj.', defs: ['乏味的', '冗长的'] }], tags: ['CET6'] },
]
